CREATE TABLE IF NOT EXISTS country(
Id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
Name VARCHAR(20) NOT NULL,
Language VARCHAR(20) NOT NULL,
Paysystem VARCHAR(20) NOT NULL
);

SELECT * FROM country;

CREATE TABLE IF NOT EXISTS location(
Id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
Name VARCHAR(20) NOT NULL,
Address VARCHAR(20) NOT NULL,
Details TEXT NOT NULL,
CountryId INT NOT NULL,
FOREIGN KEY (CountryId) REFERENCES country(Id)
);

CREATE TABLE IF NOT EXISTS department(
Id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
Name VARCHAR(50) NOT NULL,
Address VARCHAR(20) NOT NULL,
Details TEXT NOT NULL,
LocationId INT NOT NULL,
FOREIGN KEY (LocationId) REFERENCES location(Id)
);

CREATE TABLE IF NOT EXISTS employee(
Id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
Firstname VARCHAR(20) NOT NULL,
Lastname VARCHAR(20) NOT NULL,
Gender ENUM ("m", "f"),
Address VARCHAR(20) NOT NULL,
Birthdate DATE NOT NULL,
Employmentdate DATE NOT NULL,
Leavingdate DATE NOT NULL,
Details TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS workassignments(
Id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
Startdate DATE NOT NULL,
Finishdate DATE NOT NULL,
Details TEXT NOT NULL,
SupervisorId INT NOT NULL,
FOREIGN KEY (SupervisorId) REFERENCES employee(Id),
DepartmentId INT NOT NULL,
FOREIGN KEY (DepartmentId) REFERENCES department(Id)
);

CREATE TABLE IF NOT EXISTS reports(
Id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
Revisiondate DATE NOT NULL,
Revisorcomments TEXT NOT NULL,
Employeecomments TEXT NOT NULL,
RevisorId INT NOT NULL,
FOREIGN KEY (RevisorId) REFERENCES employee(Id)
);

CREATE TABLE IF NOT EXISTS trainings(
Id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
Trainingdatestart DATE NOT NULL,
Trainingdatefinish DATE NOT NULL,
Results TEXT NOT NULL,
EmployeeId INT NOT NULL,
FOREIGN KEY (EmployeeId) REFERENCES employee(Id)
);

CREATE TABLE IF NOT EXISTS databaseadmin(
Id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
AdminId INT NOT NULL,
FOREIGN KEY (AdminId) REFERENCES employee(Id)
);

ALTER TABLE databaseadmin
ADD COLUMN Username VARCHAR(15) AFTER AdminId,
ADD COLUMN Password VARCHAR(200) AFTER Username;

ALTER TABLE databaseadmin
MODIFY Username VARCHAR(15) NOT NULL,
MODIFY Password VARCHAR(300) NOT NULL;